[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = off
lib_deps =
    adafruit/DHT sensor library@^1.4.7
    adafruit/Adafruit Unified Sensor@^1.1.14
monitor_speed = 115200
